name: 'Pull Request Quotes'
description: 'This action will post random quotes to your pull requests'
inputs:
  github-token:
    description: 'Github token'
    required: true
runs:
  using: 'node14'
  main: 'index.js'
